### ISSUE TITLE
Som produktägare måste jag veta huruvida vi får marknadsföra enksilda företag på facebook/instagram eller inte

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#109]
# Acceptanskriterier
- [ ] Våra inlägg måste gå i linje med kommunallagen.
- [ ] Vi måste veta vad som gäller i teorin och i praktiken.
- [ ] Vi måste veta vad som gäller vid likes på instagram
- [ ] Vi måste veta vad som gäller när det kommer till konton vi följer på instagram

**Comment by albinmartinsson91** [comment]
Rent juridiskt får man inte lyfta ett eller flera företag på facebook eller liknande. Men vi måste undersöka hur andra destinationer arbetar med dessa frågor för det fungerar inte så i praktiken.
