### ISSUE TITLE
Som besökare på visithalland vill jag kunna dela ett marknadskoncept på facebook eller andra sociala kanaler.

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#112]
# Acceptanskriterier
- [ ] Jag vill själv kunna välja vilken av bilderna som ska vara "delningsbilden".
- [ ] Jag vill kunna välja att själv skriva en delsningtext.

**Comment by albinmartinsson91** [comment]
Finns lite strul här som vi borde gå igenom. Väntar med denna sålänge.
