### ISSUE TITLE
Som besökare vill jag kunna kontakta de som ligger bakom visithalland.com

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#122]
- [x] Lägg in info@visithalland.com i footern.
- [x] Lägg in länk till instagram i footern
- [x] Lägg in länk till facebook i footern
- [x] Gör en enkel "om oss-sida".

**Comment by albinmartinsson91** [comment]
info@visithalland.com

**Comment by lisasoderholm** [comment]
@albinmartinsson91   kan vi lägga in destinationhalland.se i footern också?
