### ISSUE TITLE
Som team vill vi ha samma wordpress-miljö som resten av regionen.

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#123]
# Acceptanskriterier
- [ ] Sidan är tillgänglig på en ny server.
- [ ] Våra bilder ska finnas tillgängliga på Azures bildlagringstjänst.

**Comment by sebastiansson** [comment]
We're coming for you @davidohlin.

**Comment by sebastiansson** [comment]
Har hört från Henrik och de kan inte ge oss någon server i dagsläget. Vi får avvakta med denna.

**Comment by davidohlin** [comment]
Boooooooo 📣😮

**Comment by sebastiansson** [comment]
Note to self: Se till att cookie-notice.js fungerar som senaste versionen som ligger uppe på visithalland.com
