### ISSUE TITLE
Som innehållsansvarig måste jag få in mängder av nytt fotomaterial för att kunna marknadsföra Halland.

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#137]
Vi vill hitta en fotograf som vi kan arbeta med under en längre period och som kan åka ut och fota massor av näringslivsaktörer, platser och locals.
# Acceptanskriterier
- [ ] Hen ska kunna vara hos oss i 2-3 månader
- [ ] Hen ska fota utifrån vår tonalitet
- [ ] Hen ska ha koll på GDPR

**Comment by sebastiansson** [comment]
📸
