### ISSUE TITLE
Som besöker vill jag kunna söka på ”visit halland” på Google och få upp siten

### ISSUE THREAD

**Issue by sebastiansson** [RegionHalland/visithalland-cms#159]
# Acceptanskriterier
- [x] När man söker på ”visit halland” på Google så ska siten komma upp.

**Comment by albinmartinsson91** [comment]
<img width="811" alt="skarmklipp 2018-05-07 08 11 05" src="https://user-images.githubusercontent.com/6444149/39687334-46cc5c86-51ce-11e8-831d-b06386153c3c.png">
