### ISSUE TITLE
Som besökare vill jag kunna söka på näringslivsaktörer och platser på visithalland.com

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#25]
# Acceptanskriterier
- [x] Det ska gå att göra en sökning genom att klicka på enter.
- [ ] Söket börjar inte förrän man skrivit in minst tre bokstäver.
- [x] Sökmotorn ska kunna matcha sökningar även om de inte är helt rättstavade.
- [ ] Man ska kunna söka på nyckelord som artiklarna är taggade med.
- [x] Söket ska fungera bra i både mobil, desktop och tablet.
- [x] Sökmotorn ska kunna matcha sökningar utan ÅÄÖ

**Comment by albinmartinsson91** [comment]
Vi behöver se till att instantsearch (alltså söksidan) sorterar baserat på valt språk
