### ISSUE TITLE
Som redaktör vill jag att det ska vara enkelt att navigera i CMS:et

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#26]
# Acceptanskriterier
- [x] Det ska inte finnas några onödig fält.
- [x] Text som klistras in ska "av-formateras"
- [x] Fixa ett bättre sätt att styra de valda artiklarna

**Comment by sebastiansson** [comment]
@lisasoderholm vad menas med “Fixa ett bättre sätt att styra de valda artiklarna“? Vi skulle behöva gå igenom hur det fungerar idag och se vad vi kan förbättra.

**Comment by sebastiansson** [comment]
Sådär nu rensas viss formatering. Taggar som vi låter vara kvar är:
p,span,b,strong,i,em,h3,h4,h5,h6,ul,li,ol

Men vi tar bort klasser och id. Styles verkar inte (? @davidohlin) följa med när man klistrar in så de behöver vi inte ta bort.

**Comment by sebastiansson** [comment]
@davidohlin Kanske kan ni ha användning för funktionen också? Se kommit https://github.com/RegionHalland/visithalland-cms/commit/b596873443f77d34da2f8f7fb1d8de2b58fad4c2 och funktionen”configure_tinymce”.
