### ISSUE TITLE
Som team vill vi att webben levererar bra i googles verktyg.

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#44]
## Om user story'n

Set up för Advanced settings (permalänkar, crawl errors, redirects, breadcrumbs, sitemaps)

## Acceptanskriterier

- [x] Meta-taggar och Title ska fungera på samtliga sidor 
- [ ] En korrekt och uppdaterad sitemap ska finnas registrerad i Search Console  (Väntar på live)
- [x] Samtliga sidor ska kontrolleras och godkännas av Google Structured Data Testing Tool med korrekt upptaggning
- [x] Facebooks Open Graph Object Debugger ska inte visa några errors eller varningar
- [ ] Pinterest Rich Pin Validator ska inte visa några errors eller varningar (Väntar med p.g.a. bugg)
- [x] Samtliga sidor bör klara Google Mobile Friendly Test
- [x] Samtliga sidor bör köras genom Google Page Speed och en lista på åtgärder som är möjliga att genomföra ska tas fram
- [x] Gå igenom stegen för setup i Yoast 
- [ ] Gå igenom vilka döda länkar vi har och åtgärda via Yoast Redirects (Väntar med p.g.a. new sitemap)

## Bra att ha
https://moz.com/blog/how-to-achieve-100100-with-the-google-page-speed-test-tool
https://www.keycdn.com/blog/google-pagespeed-insights-wordpress/

**Comment by albinmartinsson91** [comment]
Förslag på acceptanskriter:

- Yoast ska inte ge några errors
- Vi ska köra siten och dess sidor genom Googles verktyg och se till så att vi har alla taggar vi behöver (meta, og, title, keywords osv).
- Siten ska sättas som "Indexerbar" i yoast
- SEO ska fungera för språkversioner

@lisasoderholm

**Comment by albinmartinsson91** [comment]
Kort om Meta Tags - Det verkar inte finnas några best practices här. Mest att meta tagen bör beskriva innehållet på sidan och inte vara alldeles för lång. Vår formula ser ut såhär idag Artikel/Sidtitel - Visithalland. Tror därför det är viktigt att vi skriva rubriker som istället för "Kattegattleden längs sveriges västkust" är "Cykla längs kattegattleden och upplev Sveriges västkust" så att länkarna som man ser i Google är mer klickvänliga. 

@lisasoderholm @sebastiansson

**Comment by albinmartinsson91** [comment]
Ang. Featured Content/Rich Cards osv: Vi skulle behöva gå igenom vilka Custom Fields som används idag för att få det att fungera som vi vill. Exempelvis följer inte våra featured images med eftersom dessa ligger som custom fields och inte som Wordpress vanliga featured image. Sen behöver vi även kika på kategorierna då dessa inte registreras i Schema-plugin'et.

**Comment by albinmartinsson91** [comment]
#Att göra

https://www.keycdn.com/support/leverage-browser-caching/
https://wordpress.org/support/topic/browser-caching-expiration-time-not-set/

**Comment by albinmartinsson91** [comment]
## Svarstid från server
Vi skulle behöva se över svarstiden från servern

**Comment by albinmartinsson91** [comment]
## Att tänka på

- [ ] Har vi en registrerad sitemap kopplad till Search Console?

- [ ] Har vi några redirects eller 404 i Search Console som vi behöver reda ut? Spana även i Yoast-plugin
