### ISSUE TITLE
Som campingintresserad norrman vill jag få reda på att Halland är ett bra alternativ för semestern.

### ISSUE THREAD

**Issue by lisasoderholm** [RegionHalland/visithalland-cms#64]
Vi vill göra en digital kampanj för norrmän på facebook och instagram.
- [x] Kampanjen/annonsen ska rikta sig till norrmän som bor max 6 timmar från Halland.
- [ ] Kampanjen/annonsen ska innehålla både camping som boendeform och passande aktiviteter.
- [ ] Kampanjen/annonsen ska ske i kanaler där målgruppen vanligtvis rör sig.
- [ ] Kampanjen/annonsen ska visa att det finns mycket att göra i Halland.
- [ ] Sätt upp en test-kampanj i Canvas.
- [ ] Vi ska ha flera olika annonser att testa mellan.
- [ ] Kampanjens budget får inte överstiga 5000 kronor.

**Comment by simpel** [comment]
För norrmän va? Eller gillar vi som inte? :)
